config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

  resources :pokemons, only: %i[index show new create destroy] do
    resources :bookings, only: %i[create]
  end

  resources :bookings, only: %i[show update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = ['pending', 'validated', 'rejected'].freeze
  belongs_to :pokemon
  belongs_to :user
  validates :start_date, :end_date, presence: true
  validates :status, inclusion: { in: STATUS }
  scope :pending_and_validated, -> { where(" status = 'pending' OR status = 'validated' ") }
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, :description, :price, presence: true
end

app/models/pokemonbase.rb
class Pokemonbase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  has_many :bookings
  has_many :pokemons
  has_many :bookings_owner, through: :pokemons, source: :bookings
  has_many :pokemons_reserved, through: :bookings, source: :pokemon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: user_params)
    devise_parameter_sanitizer.permit(:account_update, keys: user_params)
    devise_parameter_sanitizer.permit(:sign_in, keys: user_params)
    devise_parameter_sanitizer.permit(:accept_invitation, keys: user_params)
  end

  def user_params
    %i[username city address phone_number email].freeze
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    @booking = Booking.new(booking_params_booker)
    @booking.user_id = current_user.id
    @booking.pokemon_id = @pokemon.id
    if @booking.save!
      redirect_to dashboard_path
    else
      render
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params_owner)
    redirect_to dashboard_path
  end

  def show
    @booking = Booking.find(params[:id])
    @user = User.find(@booking.user_id)
  end

  private

  def booking_params_booker
    params.require(:booking).permit(:start_date, :end_date)
  end

  def booking_params_owner
    params.require(:booking).permit(:status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @pokemons = Pokemon.all

  end

  # Pour les bookers :
  # - mes pokemons que je loue
  # - Voir ses réservations

  # Pour les owners :
  # - mes pokemons que je détiens (en tant que proprio) + leur statuts
  # - Mes réservation en tant que owner

  def dashboard
    @bookings_booker = current_user.bookings
    @bookings_owner = current_user.bookings_owner
    @pokemons_booker = current_user.pokemons_reserved
    @pokemons_owner = current_user.pokemons
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @pokemons = Pokemon.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @pokemons = Pokemon.all
    end
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @booking = Booking.new
    @user = User.find(@pokemon.user_id)
  end

  def new
    @pokemon = Pokemon.new
    @pokemons = Pokemonbase.all
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokebase = Pokemonbase.find(params[:pokemon][:id].to_i)
    @pokemon.name = @pokebase.name
    @pokemon.attack = @pokebase.attack
    @pokemon.defense = @pokebase.defense
    @pokemon.speed = @pokebase.speed
    @pokemon.hp = @pokebase.hp
    @pokemon.image_url = @pokebase.image_url
    @pokemon.types = @pokebase.types
    @pokemon.abilities = @pokebase.abilities
    @pokemon.user = current_user
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      @pokemons = Pokemonbase.all
      render :new
    end
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<main data-barba="container" data-barba-namespace="show">
  <div class="show-show">
    <div class="pokeball"><%= image_tag "pokeball.png" %></div>
    <h1 class="text-center"> <%= @booking.pokemon.name %> </h1>
    <div class="pokemon-show">
      <div class="pokemon-show-stats">
        <div class="col-lg-3 col-md-2  d-flex flex-wrap justify pokemon-show-stats-wrapper">
          <table class="table table-borderless">
            <tr>
              <td class="text-right font-weight-bold">HP</td>
              <td>
                <div class='barre-show'><label for="determinate"><%=@booking.pokemon.hp%>&nbsp;</label><progress id="determinate"  value="<%=@booking.pokemon.hp%>" min="0" max="200"><%=@booking.pokemon.hp%></progress></div>
              </td>
            </tr>
            <tr>
              <td class="text-right font-weight-bold">Attack</td>
              <td>
                <div class='barre-show'><label for="determinate"><%=@booking.pokemon.attack%>&nbsp;</label><progress id="determinate"  value="<%=@booking.pokemon.attack%>" min="0" max="155"> <%=@booking.pokemon.attack%></progress></div>
              </td>
            </tr>
            <tr>
              <td class="text-right font-weight-bold">Defence</td>
              <td>
                <div class='barre-show'><label for="determinate"> <%=@booking.pokemon.defense%> &nbsp;</label><progress id="determinate"  value="<%=@booking.pokemon.defense%>" min="0" max="100"> <%=@booking.pokemon.defense%> </progress></div>
              </td>
            </tr>
            <tr>
              <td class="text-right font-weight-bold">Speed</td>
              <td>
                <div class='barre-show'><label for="determinate"> <%=@booking.pokemon.speed%>&nbsp; </label><progress id="determinate"  value="<%=@booking.pokemon.speed%>" min="0" max="100"> <%=@booking.pokemon.speed%> </progress></div>
              </td>
            </tr>
            <tr>
              <td class="text-right font-weight-bold">Type</td>
              <td><%= @booking.pokemon.types.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></td>
            </tr>
            <tr>
              <td class="text-right font-weight-bold">Abilities</td>
              <td><%= @booking.pokemon.abilities.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></td>
            </tr>
            <tr>
              <td class="text-right font-weight-bold">Trainer</td>
              <td><%= @booking.pokemon.user.username%></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="pokemon-show-img">
        <%= image_tag @booking.pokemon.image_url, alt: @booking.pokemon.name %>
      </div>
      <div class="pokemon-show-booking ">
        <table class="table table-borderless">
          <tr>
            <td class="text-right font-weight-bold ">From :</td>
            <td><%= @booking.start_date.strftime("%A %d %B, %Y") %></td>
          </tr>
          <tr>
            <td class="text-right font-weight-bold ">To :</td>
            <td><%= @booking.end_date.strftime("%A %d %B, %Y") %></td>
          </tr>
          <tr>
            <td class="text-right font-weight-bold ">Price / Day :</td>
            <td><%= @booking.pokemon.price%> €</td>
          </tr>
          <tr>
            <td class="text-right font-weight-bold ">Total Amount :</td>
            <td>
              <%nbd = (@booking.end_date - @booking.start_date).to_i/86400.to_i%>
              <%if nbd == 0 %>
                <% nbd = 1%>
              <% end %>
              <%=  (nbd * @booking.pokemon.price).to_s(:delimited) %> €
            </td>
          </tr>
          <tr>
            <td class="text-right font-weight-bold ">Rented by : <%= @booking.user.id %></td>
            <td><%= @booking.user.username%></td>
          </tr>
          <tr>
            <td class="text-right font-weight-bold ">Status :</td>
            <% if current_user.id == @booking.pokemon.user.id  %>
              <td>
                <% if @booking.status == 'pending' %>
                  <%= simple_form_for(@booking) do |f| %>
                    <%= f.input :status, prompt: '',collection: ['validated', 'rejected'], label:false %>
                    <%= f.submit "Update", :class => "more_info-res"%>
                  <% end %>
                <% else %>
                  <% if @booking.status =='validated' %>
                    <p class='pokemon-booking pokemon-booking-validated'><%= @booking.status.capitalize %></p>
                  <% elsif @booking.status =='pending' %>
                    <p class='pokemon-booking pokemon-booking-pending'><%= @booking.status.capitalize %></p>
                  <% else %>
                    <p class='pokemon-booking pokemon-booking-refused'><%= @booking.status.capitalize %></p>
                  <% end %>
                <% end %>
              </td>
            <% else %>
              <td>
                <% if @booking.status =='validated' %>
                  <p class='pokemon-booking pokemon-booking-validated'><%= @booking.status.capitalize %></p>
                <% elsif @booking.status =='pending' %>
                  <p class='pokemon-booking pokemon-booking-pending'><%= @booking.status.capitalize %></p>
                <% else %>
                  <p class='pokemon-booking pokemon-booking-refused'><%= @booking.status.capitalize %></p>
                <% end %>
              </td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
    <div class="description-show container">
      <h2 class="text-center"><%= @booking.pokemon.description %></h2>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poke810</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <script defer src="https://unpkg.com/@barba/core"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/@barba/core"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.9.4/lottie.min.js" integrity="sha512-ilxj730331yM7NbrJAICVJcRmPFErDqQhXJcn+PLbkXdE031JJbcK87Wt4VbAK+YY6/67L+N8p7KdzGoaRjsTg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body data-barba="wrapper ">
    <div class="transition" ></div>
      <%= render 'shared/navbar' %>
      <%= yield %>
    </body>
  </html>

app/views/pages/dashboard.html.erb
<main data-barba="container" data-barba-namespace="dashboard">
  <div class="container-fluid">
    <div class="dashboard">
      <h2>My pokemon currently available on the platform</h2>
      <div class="pokemons-dashboard swiper-container">
        <div class="swiper-wrapper">
          <div class="add-pokemon">
            <div class="pokemon-img">
              <%=image_tag 'add_pokemon.png', alt: 'add pokemon' %>
            </div>
            <%= link_to new_pokemon_path do %>
              <div class="more_info">Add a new pokemon</div>
            <% end %>
          </div>
          <% @pokemons_owner.reverse.each do |pokemon| %>
            <div class="swiper-slide">
              <div class='pokemon-card'>
                <div class="pokemon-img">
                  <%=image_tag pokemon.image_url, alt: pokemon.name if pokemon.image_url != nil%>
                </div>

                <div class='pokemon-infos'>
                  <h2 class='text-center font-weight-bold name'><%= pokemon.name %></h2>
                  <div class='barre-home'><label for="determinate">HP:&nbsp; </label><progress id="determinate"  value="<%=pokemon.hp%>" min="0" max="155"> 50% </progress></div>
                </div>
                <div>
                  <%status = 'Available'%>
                  <%pokemon.bookings.pending_and_validated.each do |b|%>
                    <%if b.start_date <= Date.today && b.end_date >= Date.today%>
                      <%status = "Currently Rented"%>
                    <%end%>
                  <%end%>
                  <p><%=status%></p>
                </div>
                <%= link_to pokemon_path(pokemon) do %>
                  <div class="more_info">More info</div>
                <% end%>
              </div >

            </div>
          <% end %>
        </div>
      </div>
      <div class='reservation-container'>
        <h2>My reservations </h2>
        <h3>As renter</h3>
        <div class="pokemons-dashboard swiper-container">
          <div class="swiper-wrapper">
            <% @bookings_booker.reverse.each do |booking| %>
              <div class="swiper-slide">
                <div class='pokemon-card'>
                  <div class="pokemon-img">
                    <%=image_tag booking.pokemon.image_url, alt: booking.pokemon.name if booking.pokemon.image_url != nil%>
                  </div>
                  <div class='pokemon-infos'>
                    <h2 class='text-center font-weight-bold name'><%= booking.pokemon.name %></h2>
                    <div class='barre-home'><label for="determinate">HP:&nbsp; </label><progress id="determinate"  value="<%=booking.pokemon.hp%>" min="0" max="155"> 50% </progress></div>
                  </div>
                  <div class="pokemon-stats-wrapper">
                    <div >
                      <p><%= booking.start_date.strftime("From %d %B, %y") %> </p>
                      <p><%= booking.end_date.strftime("To %d %B, %y") %> </p>
                    </div>
                    <div class="status-as-renter">
                      <% if booking.status =='validated' %>
                        <p class='pokemon-booking pokemon-booking-validated'><%= booking.status.capitalize %></p>
                      <% elsif booking.status =='pending' %>
                        <p class='pokemon-booking pokemon-booking-pending'><%= booking.status.capitalize %></p>
                      <% else %>
                        <p class='pokemon-booking pokemon-booking-refused'><%= booking.status.capitalize %></p>
                      <% end %>
                    </div>
                  </div>
                  <div class="total">
                    <%nbd = (booking.end_date - booking.start_date).to_i/86400.to_i%>
                    <%if nbd == 0 %>
                      <% nbd = 1%>
                    <% end %>
                    <p> <span class="font-weight-bold">Total :</span>  <%=  (nbd * booking.pokemon.price).to_s(:delimited) %> € </p>
                  </div>
                  <%= link_to booking_path(booking) do %>
                    <div class="more_info">More info</div>
                  <% end%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <h3>As owner</h3>
        <div class="pokemons-dashboard swiper-container">
          <div class="swiper-wrapper">
            <% @bookings_owner.sort.reverse.each do |booking| %>
              <div class="swiper-slide">
                <div class='pokemon-card'>
                  <div class="pokemon-img">
                    <%=image_tag booking.pokemon.image_url, alt: booking.pokemon.name if booking.pokemon.image_url != nil%>
                  </div>
                  <div class='pokemon-infos'>
                    <h2 class='text-center font-weight-bold name'><%= booking.pokemon.name %></h2>
                    <div class='barre-home'><label for="determinate">HP:&nbsp; </label><progress id="determinate"  value="<%=booking.pokemon.hp%>" min="0" max="155"> 50% </progress></div>
                  </div>
                  <div class="pokemon-stats-wrapper">
                    <div >
                      <p><%= booking.start_date.strftime("From %d %B, %y") %> </p>
                      <p><%= booking.end_date.strftime("To %d %B, %y") %> </p>
                    </div>
                    <div class="total">
                      <%nbd = (booking.end_date - booking.start_date).to_i/86400.to_i%>
                      <%if nbd == 0 %>
                        <% nbd = 1%>
                      <% end %>
                      <p> <span class="font-weight-bold">Total :</span>  <%=  (nbd * booking.pokemon.price).to_s(:delimited) %> € </p>
                    </div>
                  </div>
                  <div class="status-as-renter">
                    <% if booking.status == 'pending' %>
                      <%= simple_form_for(booking) do |f| %>
                        <%= f.input :status, prompt: '',collection: ['validated', 'rejected'], label:false %>
                        <%= f.submit "Update", :class => "more_info-res"%>
                      <% end %>
                    <% else %>
                      <% if booking.status =='validated' %>
                        <p class='pokemon-booking pokemon-booking-validated'><%= booking.status.capitalize %></p>
                      <% elsif booking.status =='pending' %>
                        <p class='pokemon-booking pokemon-booking-pending'><%= booking.status.capitalize %></p>
                      <% else %>
                        <p class='pokemon-booking pokemon-booking-refused'><%= booking.status.capitalize %></p>
                      <% end %>
                    <% end %>
                  </div>
                  <%= link_to booking_path(booking) do %>
                    <div class="more_info">More info</div>
                  <% end%>
                </div>

              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </main>

app/views/pages/home.html.erb
<main data-barba="container" data-barba-namespace="home">
  <div class="banner-home">
    <h1 class = 'text-center banner-title' style='text-shadow: 2px 2px 3px rgba(0,0,0,0.8); margin-top:100px'>RENT YOUR FAVORITE POKEMONS FOR A DAY, A WEEK OR EVEN A MONTH </h1>
  </div>
  <div class="container-fluid">
    <h3>The most popular</h3>
    <div class="cards-home swiper-container">
      <% pokemon_asked = @pokemons.order(id: :desc).limit(5) %>
      <div class="swiper-wrapper">
        <% pokemon_asked.each do |pokemon| %>
          <div class="swiper-slide">
            <div class='pokemon-card'>
              <div class="pokemon-img">
                <%=image_tag pokemon.image_url, alt: pokemon.name if pokemon.image_url != nil%>
              </div>
              <div class='pokemon-infos'>
                <h2 class='text-center font-weight-bold name'><%= pokemon.name %></h2>
                <div class='barre-home'><label for="determinate">HP:&nbsp; </label><progress id="determinate"  value="<%=pokemon.hp%>" min="0" max="155"> 50% </progress>
                </div>
              </div>
              <div class="pokemon-stats-wrapper">
                <div class="pokemon-stats pokemon-stats--types">
                  <p><%=pokemon.types.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></p>
                  <p class="font-weight-bold">Type</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--attack">
                  <p><%= pokemon.attack %></p>
                  <p class="font-weight-bold">Attack</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--def">
                  <p><%= pokemon.defense %></p>
                  <p class="font-weight-bold">Def</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--speed">
                  <p><%= pokemon.speed %></p>
                  <p class="font-weight-bold">Speed</p>
                </div>
              </div>
              <div class="wrapper-horizontal">
              </div>
              <div class="pokemon-stats pokemon-stats--abilities">
                <p class="font-weight-bold">Abilities</p>
                <p><%=pokemon.abilities.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></p>
              </div>
              <div class="footer">
                <p class='font-weight-bold'><%= pokemon.price %> € / day</p>
              </div>
              <%= link_to pokemon_path(pokemon) do %>
                <div class="more_info more_info-home">More info
                </div>
              <% end%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <h3>The most powerfull</h3>
    <div class='cards-home swiper-container'>
      <%pokemon_powerful = @pokemons.order(attack: :desc).limit(5)%>
      <div class="swiper-wrapper">
        <% pokemon_powerful.each do |pokemon| %>
          <div class="swiper-slide">
            <div class='pokemon-card'>
              <div class="pokemon-img">
                <%=image_tag pokemon.image_url, alt: pokemon.name if pokemon.image_url != nil%>
              </div>
              <div class='pokemon-infos'>
                <h2 class='text-center font-weight-bold name'><%= pokemon.name %></h2>
                <div class='barre-home'><label for="determinate">HP:&nbsp; </label><progress id="determinate"  value="<%=pokemon.hp%>" min="0" max="155"> 50% </progress>
                </div>
              </div>
              <div class="pokemon-stats-wrapper">
                <div class="pokemon-stats pokemon-stats--types">
                  <p><%=pokemon.types.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></p>
                  <p class="font-weight-bold">Type</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--attack">
                  <p><%= pokemon.attack %></p>
                  <p class="font-weight-bold">Attack</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--def">
                  <p><%= pokemon.defense %></p>
                  <p class="font-weight-bold">Def</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--speed">
                  <p><%= pokemon.speed %></p>
                  <p class="font-weight-bold">Speed</p>
                </div>
              </div>
              <div class="wrapper-horizontal">
              </div>
              <div class="pokemon-stats pokemon-stats--abilities">
                <p class="font-weight-bold">Abilities</p>
                <p><%=pokemon.abilities.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></p>
              </div>
              <div class="footer">
                <p><strong><%= pokemon.price %> € / day</strong></p>
              </div>
              <%= link_to pokemon_path(pokemon) do %>
                <div class="more_info more_info-home">More info</div>
              <% end%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <h3>The most attractive</h3>
    <div class="cards-home swiper-container">
      <%pokemon_cheaper = @pokemons.order(:price).limit(5)%>
      <div class="swiper-wrapper">
        <% pokemon_cheaper.each do |pokemon| %>
          <div class="swiper-slide">
            <div class='pokemon-card'>
              <div class="pokemon-img">
                <%=image_tag pokemon.image_url, alt: pokemon.name if pokemon.image_url != nil%>
              </div>
              <div class='pokemon-infos'>
                <h2 class='text-center font-weight-bold name'><%= pokemon.name %></h2>
                <div class='barre-home'><label for="determinate">HP:&nbsp; </label><progress id="determinate"  value="<%=pokemon.hp%>" min="0" max="155"> 50% </progress>
                </div>
              </div>
              <div class="pokemon-stats-wrapper">
                <div class="pokemon-stats pokemon-stats--types">
                  <p><%=pokemon.types.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></p>
                  <p class="font-weight-bold">Type</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--attack">
                  <p><%= pokemon.attack %></p>
                  <p class="font-weight-bold">Attack</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--def">
                  <p><%= pokemon.defense %></p>
                  <p class="font-weight-bold">Def</p>
                </div>
                <span class="wrapper-vertical"></span>
                <div class="pokemon-stats pokemon-stats--speed">
                  <p><%= pokemon.speed %></p>
                  <p class="font-weight-bold">Speed</p>
                </div>
              </div>
              <div class="wrapper-horizontal"></div>
              <div class="pokemon-stats pokemon-stats--abilities">
                <p class="font-weight-bold">Abilities</p>
                <p><%=pokemon.abilities.gsub(/[^0-9a-z ]/i, '').split.join(' | ').titleize %></p>
              </div>
              <div class="footer">
                <p><strong><%= pokemon.price %> € / day</strong></p>
              </div>
              <%= link_to pokemon_path(pokemon) do %>
                <div class="more_info more_info-home">More info</div>
              <% end%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</main>

app/views/pokemons/create.html.erb
<main data-barba="container" data-barba-namespace="create">
  <h1>Pokemons#create</h1>
  <p>Find me in app/views/pokemons/create.html.erb</p>
</main>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path,:"data-turbolinks" => false,  class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <div class="search">
    <%= form_tag pokemons_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control zone-text",
        placeholder: "Find a pokemon"%>
    <% end %>
    <%= image_tag ("search.png"), class: "searchbtn" %>
    <li class="nav-item dropdown">
      <%= image_tag "sacha.png", class: "avatar dropdown-toggle avatar-circle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
        <%= link_to "Pokemons", pokemons_path, class: "dropdown-item" %>
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
          <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
        <% end %>
      </div>
    </li>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item">
        <%= link_to "Pokemons", pokemons_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>